#define STATUS_SUCCESS  0x000

#define STATUS_ERROR_IO 0xF01
#define STATUS_ERROR_PARSING_NUMBER 0xF02
#define STATUS_ERROR_PARSING_INCOMPLETE 0xF03
#define STATUS_ERROR_PARSING_EXISTANT_EDGE 0xF04

#define STATUS_NO_PATH 0xA01
